package greek

// Greek

// TODO: These are just lowercase, should probably be a map of maps dividning
// upper and lowercase.
var Symbols = map[string]map[string]string{
	"upper": map[string]string{
		"alpha":   "Α",
		"beta":    "Β",
		"gamma":   "Γ",
		"delta":   "Δ",
		"epsilon": "Ε",
		"zeta":    "Ζ",
		"eta":     "Η",
		"theta":   "Θ",
		"iota":    "Ι",
		"kappa":   "Κ",
		"lambda":  "Λ",
		"mu":      "Μ",
		"nu":      "Ν",
		"xi":      "Ξ",
		"omicron": "Ο",
		"pi":      "Π",
		"ro":      "Ρ",
		"sigma":   "Σ",
		"tau":     "Τ",
		"upsilon": "Υ",
		"phi":     "Φ",
		"chi":     "Χ",
		"psi":     "Ψ",
		"omega":   "Ω",
	},
	"lower": map[string]string{
		"alpha":     "α",
		"beta":      "β",
		"gamma":     "γ",
		"delta":     "δ",
		"epsilon":   "ε",
		"zeta":      "ζ",
		"eta":       "η",
		"theta":     "θ",
		"iota":      "ι",
		"kappa":     "κ",
		"lambda":    "λ",
		"mu":        "μ",
		"nu":        "ν",
		"xi":        "ξ",
		"omicron":   "ο",
		"pi":        "π",
		"ro":        "ρ",
		"sigma":     "σ",
		"sigma_alt": "ς", // This verison is used at the end of words
		"tau":       "τ",
		"upsilon":   "υ",
		"phi":       "φ",
		"chi":       "χ",
		"psi":       "ψ",
		"omega":     "ω",
	},
}
